### ISSUE TITLE
[Epic]: 

### ISSUE THREAD

**Issue by RSoulatIOHK** [input-output-hk/plutus-high-assurance-template#1]
### Acknowledgements

- [X] I am a member of the team

### Epic description

gtgtgt

### Acceptance Criteria

```[tasklist]
## (What are the acceptance criteria for this Epic?)
- [ ] Specify the feature
- [ ] Develop the feature
- [ ] Test the feature
```

### Priority

None
